[package]
name = "explorer"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "explorer"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
chrono = "0.4"
rand = { version = "0.8.4", features = ["alloc"] }
rand_pcg = "0.3.1"
rustler = "0.25.0"
thiserror = "1"

# This is because when using GCC on Windows MiMalloc won´t compile
[target.'cfg(not(all(windows, target_env = "gnu")))'.dependencies]
mimalloc = { version = "*", default-features = false }

[dependencies.polars]
git = "https://github.com/pola-rs/polars.git"
rev = "3ba710641c9b52a412263879d71a601d5e130238"
default-features = false
features = [
  "cross_join",
  "dtype-date",
  "dtype-datetime",
  "json",
  "parquet",
  "rows",
  "sort_multiple",
  "strings",
  "temporal",
  "cum_agg",
  "rolling_window",
  "decompress",
  "ipc"
]
